import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppProps } from "next/app";
import store from "../store/store";
import { StoreProvider } from "@/store/storeProvider";
import NavBar from "./atoms/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <NavBar />

          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
